### PR TITLE
Determine if monitor is internally connected

### LINKED ISSUE #6: (Windows) Attempts to use incorrect API (IoctlSetBrightnessFailed) on DDC/CI monitor
One of my users is seeing the IoctlSetBrightnessFailed error for their external monitors:

https://github.com/jacob-pro/solar-screen-brightness/issues/17

I think we need to change this section of code to be more reliable:

https://github.com/stephaneyfx/brightness/blob/a74a8222b2c68b3a1ea3ec2aaf4186725c5e3e5a/src/windows.rs#L106-L117

I suggest we try the [GetMonitorCapabilities](https://docs.microsoft.com/en-us/windows/win32/api/highlevelmonitorconfigurationapi/nf-highlevelmonitorconfigurationapi-getmonitorcapabilities) during the brightness_devices() stage to more reliably detect if a monitor supports DDC/CI or not first.

I will work on a PR and testing this in a bit...

### PR DESCRIPTION
**Pull request by jacob-pro**
The main change here is that QueryDisplayConfig() API is used to find out the output technology for each device, allowing us to more reliably determine whether to use the DDC/CI or Ioctl API to get/set brightness.
 
This will fix https://github.com/stephaneyfx/brightness/issues/6 where currently the crate is incorrectly attempting to use the Ioctl API to control an externally connected display.

This also upgrades the windows dependency to its latest version, which removes the need for a separate bindings crate.

### CODE REVIEW

File: src/windows.rs [hunk 1]
```diff
@@ -86,238 +121,320 @@ impl crate::Brightness for Brightness {
...
+            ioctl_set_display_brightness(self, new_value)?;
+        } else {
+            let current = ddcci_get_monitor_brightness(self)?;
+            let new_value = current.percentage_to_current(percentage);
+            ddcci_set_monitor_brightness(self, new_value)?;
+        })
     }
 }
 
 pub fn brightness_devices() -> impl Stream<Item = Result<Brightness, SysError>> {
```
Comment (jacob-pro) [inline src/windows.rs:144]: I have broken up parts of `brightness_devices()` into their own functions; it was becoming difficult to read because of both its length and depth of nested blocks (vs the line length limit).
This has also created room for me to add more detailed rustdoc style comments to each of the new functions.
Hopefully this is ok?

**Comment by jacob-pro** [comment]
Good news: this has been confirmed to fix the issue a user was seeing:
https://github.com/jacob-pro/solar-screen-brightness/issues/17

**Comment by stephaneyfx** [comment]
Thank you for all your work on the Windows implementation of this crate and sorry for the delay of my review. I should have more time to review this PR this weekend.

File: src/windows.rs (hunk 1 above)
Comment (stephaneyfx) [reply src/windows.rs:144]: Shorter and simpler functions and documentation are always welcome. Thank you!

File: src/windows.rs [hunk 2]
```diff
@@ -42,20 +49,41 @@ pub trait BrightnessExt {
...
+        self.output_technology == DISPLAYCONFIG_OUTPUT_TECHNOLOGY_INTERNAL
+    }
+}
+
+/// A safe wrapper for a physical monitor handle that implements `Drop` to call `DestroyPhysicalMonitor`
 struct WrappedPhysicalMonitor(HANDLE);
 
+impl fmt::Debug for WrappedPhysicalMonitor {
+    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
+        f.write_str(format!("{}", self.0 .0).as_str())
```
Comment (stephaneyfx) [inline src/windows.rs]: This avoids a temporary `String` and is a little simpler:
```rust
write!(f, "{}", self.0.0)
```

File: src/windows.rs [hunk 3]
```diff
@@ -64,9 +92,15 @@ impl Drop for WrappedPhysicalMonitor {
     }
 }
 
-#[derive(Debug)]
+/// A safe wrapper for a windows HANDLE that implements `Drop` to call `CloseHandle`
 struct WrappedFileHandle(HANDLE);
 
+impl fmt::Debug for WrappedFileHandle {
+    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
+        f.write_str(format!("{}", self.0 .0).as_str())
```
Comment (stephaneyfx) [inline src/windows.rs]:
```rust
write!(f, "{}", self.0.0)
```

File: src/windows.rs [hunk 4]
```diff
@@ -86,238 +121,318 @@ impl crate::Brightness for Brightness {
...
+                    }))
+                })
+                .collect()
+        }))
+        .right_stream()
+    }
+}
+
+/// Returns a `HashMap` of Device Path to `DISPLAYCONFIG_TARGET_DEVICE_NAME`.\
+/// This can be used to find the `DISPLAYCONFIG_VIDEO_OUTPUT_TECHNOLOGY` for a monitor.\
```
Comment (stephaneyfx) [inline src/windows.rs:202]: Why are there trailing backslashes?

File: src/windows.rs [hunk 5]
```diff
@@ -86,238 +121,318 @@ impl crate::Brightness for Brightness {
...
+/// The output technology is used to determine if a device is an internal or external.
```
Comment (stephaneyfx) [inline src/windows.rs]: Should it be "is internal or external" (without "an")?

File: src/windows.rs [hunk 6]
```diff
@@ -86,238 +121,318 @@ impl crate::Brightness for Brightness {
...
+                _ => Some(Err(SysError::DisplayConfigGetDeviceInfoFailed(
+                    WinError::from_win32(),
+                ))),
+            }
+        })
+        .collect()
+}
+
+/// Calls `EnumDisplayMonitors` and returns a list of `HMONITOR` handles.\
+/// Note that a `HMONITOR` is a logical construct that may correspond to multiple physical monitors.\
```
Comment (stephaneyfx) [inline src/windows.rs:251]: Remove trailing backslashes?

File: src/windows.rs [hunk 7]
```diff
@@ -86,238 +121,318 @@ impl crate::Brightness for Brightness {
...
-                                device_key: wchar_to_string(&display_device.DeviceKey),
-                            }))
-                        })
-                        .collect()
-                }))
-                .right_stream()
-            }
+        .map_err(|e| SysError::GetMonitorInfoFailed(e))?;
+    Ok((0..)
+        .map(|device_number| {
```
Comment (stephaneyfx) [inline src/windows.rs]: `.map(...).take_while(Option::is_some).flatten()` can now be simplified to `.map_while(...)`.

File: src/windows.rs [hunk 8]
```diff
@@ -86,238 +121,318 @@ impl crate::Brightness for Brightness {
...
+            .then(|| device)
+        })
+        .take_while(Option::is_some)
+        .flatten()
+        .filter(|device| flag_set(device.StateFlags, DISPLAY_DEVICE_ACTIVE))
+        .collect())
+}
+
+/// Opens and returns a file handle for a display device using its DOS device path.\
+/// These handles are required for the `DeviceIoControl` API for internal displays, a handle
```
Comment (stephaneyfx) [inline src/windows.rs]: Unless I misunderstood the sentence, shouldn't "a handle" be the start of a new sentence (so period instead of comma)?

File: src/windows.rs [hunk 9]
```diff
@@ -86,238 +121,318 @@ impl crate::Brightness for Brightness {
...
+                // There doesn't seem to be any way to directly associate a physical monitor
+                // handle with the equivalent display device, other than by array indexing
+                // https://stackoverflow.com/questions/63095216/how-to-associate-physical-monitor-with-monitor-deviceid
+                return vec![Err(SysError::EnumerationMismatch)];
+            }
+            physical_monitors
+                .into_iter()
+                .zip(display_devices)
+                .filter_map(|(physical_monitor, mut display_device)| {
+                    let handle = match get_file_handle_for_display_device(&mut display_device) {
```
Comment (stephaneyfx) [inline src/windows.rs]: It looks like it's possible for this handle to be leaked (there are exit points before it is wrapped in `WrappedFileHandle`). I suggest making `get_file_handle_for_display_device` return `Option<Result<WrappedFileHandle, SysError>>` to avoid this issue.

**Review by stephaneyfx — CHANGES_REQUESTED** [review]
Thank you again for investigating this issue and fixing it. I apologize for the time it took me to review it. I also really appreciate that you took the time to update the `windows` dependency -- I was not fond of the separate binding crate.

File: src/windows.rs (hunk 4 above)
Comment (jacob-pro) [reply src/windows.rs:202]: I did this because when you generate the docs (`cargo doc --open`) it puts them on a new line instead of a wall of text. But this is obviously just formatting preference - so if you would like it differently I'm quite happy to change it

Comment (stephaneyfx) [reply src/windows.rs:202]: Thank you for explaining. That's fine by me.

File: src/windows.rs (hunk 6 above)
Comment (stephaneyfx) [reply src/windows.rs:251]: @jacob-pro explained that they introduce a new line.

File: src/windows.rs (hunk 2 above)
Comment (jacob-pro) [reply src/windows.rs]: fixed

File: src/windows.rs (hunk 5 above)
Comment (jacob-pro) [reply src/windows.rs]: fixed

File: src/windows.rs (hunk 7 above)
Comment (jacob-pro) [reply src/windows.rs]: I think this was your code lol, anyway it is now fixed.

File: src/windows.rs (hunk 8 above)
Comment (jacob-pro) [reply src/windows.rs]: Hopefully it is more readable now?

File: src/windows.rs (hunk 9 above)
Comment (jacob-pro) [reply src/windows.rs]: Yep that is a good catch, have fixed as you suggested.

File: src/windows.rs (hunk 7 above)
Comment (stephaneyfx) [reply src/windows.rs]: `map_while` was added in the latest Rust 1.57.0, so I think it didn't exist when this code was originally written. Since this code appears in the diff as modified (although it might have just been moved), I reviewed it and thought it would be a nice simplification.

File: src/windows.rs (hunk 8 above)
Comment (stephaneyfx) [reply src/windows.rs]: It is. Thank you!

File: src/windows.rs (hunk 9 above)
Comment (stephaneyfx) [reply src/windows.rs]: Thank you!
